# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AccountBundle\Entity\Account:
            #algorithm: bcrypt
            algorithm: plaintext

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        account_db_provider:
            entity:
                class: AccountBundle:Account

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: account_login
                check_path: account_login
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

            logout:
                path: account_logout
                target: /